name: 反馈问题 (Bug report)
description: xxx 脚本的 xxx 功能失效了，或出现其他预期之外的问题...
title: "[脚本名称] xxx 功能失效（记得修改该标题示例，并移除该括号提示）"
labels: 反馈问题
body:
  - type: markdown
    attributes:
      value: |
        发之前，请先搜下有没有类似的 [**Issues**](https://github.com/XIU2/UserScript/issues) 问题（包括[**关闭**](https://github.com/XIU2/UserScript/issues?q=is%3Aissue+is%3Aclosed)的），请勿重复发起！  
        > [!NOTE]
        > 注意！**不接受**与其他脚本/扩展 `功能冲突` 的相关问题反馈（原因见 [#146](https://github.com/XIU2/UserScript/issues/146)）！  
        ****
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 必填，最好写上 复现问题 的步骤，越详细越好，特别是一些复杂的问题
      placeholder: 请输入...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 附加截图
      description: 可选，也可以是一些错误代码
      placeholder: 可在此粘贴图片，或点击下方 [Attach files by dragging & dropping, selecting or pasting them.] 文字来选择图片...