name: 功能建议 (Feature request)
description: xxx 脚本的 xxx 功能有什么建议，或希望添加一些新功能...
title: "[脚本名称] 希望添加 xxx 功能（记得修改该标题示例，并移除该括号提示）"
labels: 功能建议
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > ***注意：本项目已不再接受任何【新脚本请求】！***
        ****
        发之前，请先搜下有没有类似的 [**Issues**](https://github.com/XIU2/UserScript/issues) （包括[**关闭**](https://github.com/XIU2/UserScript/issues?q=is%3Aissue+is%3Aclosed)的），请勿重复发起！  

        > [!NOTE]
        > 注意！**不接受**与其他脚本/扩展 `功能冲突` 的相关问题反馈（原因见 [#146](https://github.com/XIU2/UserScript/issues/146)）！  

        另外，无论添加修改什么功能，都需要消耗大量时间与精力，因此请确保该功能建议是大家都需要的，而不是只为了满足个人小众需求！  
        ****
  - type: textarea
    id: description
    attributes:
      label: 功能需求
      description: 必填，你要什么样的功能？
      placeholder: 请输入...
    validations:
      required: true
  - type: textarea
    id: anticipation
    attributes:
      label: 预期目标
      description: 必填，你希望该功能具体是什么样子的？如果能提供 示例/截图/代码 就更好了
      placeholder: 请输入...
    validations:
      required: true